title: Simon Winter # your name (or website title) here
logo: "/images/meirl.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Lighthouses are just bald windmills in the same way that slugs are just bald snails🤔🤔🤔
  <br><br>
  <strong>Mapping Capital</strong>: how the flows of (more than) capital produce and are produced by uneven geographies.
  

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
